client:
  host: "192.168.0.11"
  port: 5000
gripper:
  modes: ["collect", "classify"]
  classifiers: ["balloon", "tennisball",]
  tactile:
    mode: "collect"
    classifier: "balloon"
    samples: 20
  motor:
    duration: 500
data:
  directory: "data"
  file: "tactile_sensor_data.csv"
  model: "model.pkl"
  columns: ["tactile_x", "tactile_y", "tactile_z", "abs_x", "abs_y", "abs_z", "magnitude"]