client:
  # host: "192.168.1.11"
  host: "127.0.0.1"
  port: 5000
gripper:
  modes: ["collect", "classify"]
  classifiers: ["ds30", "ds10", "ef50", "ef10"]
  tactile:
    mode: "collect"
    classifier: "ds30"
    samples: 20
  motor:
    duration: 500
model:
  directory: "data"
  file: "tactileData.csv"
  model: "model.pkl"
  # columns: ["tactile_x", "tactile_y", "tactile_z", "abs_x", "abs_y", "abs_z", "magnitude"]
  columns: ["x1","x2","x3","x4","x5","x6","x7","x8","x9","x10","y1","y2","y3","y4","y5","y6","y7","y8","y9","y10","z1","z2","z3","z4","z5","z6","z7","z8","z9","z10","magnitude"]